flawiddsouza/Restfox

packages/ui/src/components/RequestPanel.vue

Change default `graphqlVariables` to empty object to prevent 400 (bad data) when submit with  `graphqlVariables` is empty string

fix(ui): Request Panel > Body > GraphQL > Default query variables to empty object

---

README.md

It's worth to mention about `build-desktop` target which is mandatory for building the desktop application. It's needed during development too.

Documenting build-desktop target

---

packages/ui/src/helpers.ts

I couldn't find anywhere to put tests. Here's the problem
```
{
"name": "{{ name }}",
"emailFooter": "With kind regards, {{ name }}"
}
```
would become
```
{ "name": "simon", "emailFooter": "With kind regards, {{ name }}" }
```
but now becomes
```
{ "name": "simon", "emailFooter": "With kind regards, simon" }
```
Note: `replaceAll` was introduced in es2021, so you might want to provide a polyfill for (very) older browsers - or find some other solution to replace all instances.
Thanks for your time!

fix(ui): substitute all occurances of environment variables

---

packages/ui/src/helpers.spec.js
packages/ui/src/helpers.ts
packages/ui/vite.config.js

my environment
```javascript
{ 
"num": 1,
"str": "string",
"obj": { 
"key": "value"
}
}
```
<br />
<br />
We no longer fetch all the contents of the env and replace every occurrences one after the other.
Now we simply parse the request body, check for {{envVar}}, then look it up on environment and replace

Fix: [object Object] in request-body when {{envVariable}} is replaced by an object type

---

packages/ui/src/helpers.spec.js
packages/ui/src/helpers.ts

my environment
```javascript
{ arr: [ 1, 2, 3 ] }
```
<br />
in request ( previously  we would have to add square brackets manually )
```javascript
{ "key" : [ {{ arr }} ] }
```
<br />
in request ( now square brackets are not needed, they get added automatically if  the value is an array  )
```javascript
{ "key" : {{ arr }} }
```

update(ui): array square brackets are no longer stripped

---

Dockerfile
README.md

Added the docker build and usage method.  
I built a mirror `docker pull kiis/restfox:0.0.7` and haven’t returned to the Readme yet.  
You decide whether to add it to the Readme or build it yourself and add it to the Readme.  
I think there is a direct way The use of docker can avoid the impact caused by the environment.

feat: docker build for web standalone

---

README.md

If you run the clone instructions for web-standalone as they are, you'll encounter a syntax error. This commit changes that.

Clone instructions

---

packages/ui/src/components/modals/PluginManagerEditModal.vue
packages/ui/src/helpers.ts
packages/ui/src/plugin.js

I've taken the liberty of adding a few plugin methods that would allow access to the URL and headers of requests and responses. This also allows setting headers for requests via plugins but responses are read-only. This PR adds the following methods:
Request methods:
- context.request.getHeader('<HEADER_NAME>')
- context.request.setHeader('<HEADER_NAME>', '<HEADER_VALUE>')
- context.request.getHeaders()
- context.request.setHeaders(<HEADER_ARRAY>)
- context.request.getURL()
Response methods:
- context.response.getHeader('<HEADER_NAME>')
- context.response.getHeaders()
- context.response.getURL()

feat: Add access to the URL and headers from plugin

---

packages/electron/package.json

Apparently more people are using larger screen nowadays and they tend to use fractional scaling (especially in wayland). This is what happened when we use electron through xwayland compositor:
Both images are preserving its size and also the screenshot, but the second picture was taken from the 2.5K monitor and appears to be blurred.
Electron on the other hand already supports native wayland settings so can address this issue by providing simple Execute command:
`/usr/bin/env ELECTRON_OZONE_PLATFORM_HINT=auto restfox`
But because your `electron-build` config (especially snap) doesn't support wayland, so the command line wouldn't work and triggers segmentation error.
This PR just simply added `allowNativeWayland` option on snap build so we can activate `ELECTRON_OZONE_PLATFORM_HINT` env.

Allow native wayland options to support HiDPI screens that using fractional scaling (snap builds)

---

.github/workflows/main.yml

This should tag versions as latest as they are created (assuming you never run this for a version that's already been published).
I haven't tested it per se, but the push should include all tags, and since we're building in a completely blank environment, it should only possess the latest Docker image.
See if you can test these commands locally first @flawiddsouza to ensure nothing is pushed that we wouldn't want 🙏🏼

ci(docker): tag new version as latest

---

packages/ui/src/components/RequestPanelHeaders.vue
packages/ui/src/helpers.ts
packages/ui/tsconfig.json

if user doesn't specify the user-agent header, restfox would add it to the request to help the server identify Restfox as the HTTP requesting application or client.

feat: add user-agent to headers

---

packages/ui/src/components/RequestPanel.vue
packages/ui/src/constants.ts

- move MIME type to constants
- remove content-type header when no body is chosen
https://github.com/flawiddsouza/Restfox/assets/7845001/2315ea87-06a0-4aa4-aacc-44ad563c2e68

fix: remove content-type with no body request

---

packages/ui/src/components/ContextMenu.vue
packages/ui/src/components/Modal.vue
packages/ui/src/components/modals/EnvironmentModal.vue
packages/ui/src/components/modals/SidebarSettingsModal.vue
packages/ui/src/styles/main.css
packages/ui/src/web-components/alert-confirm-prompt.ts

The modifications are as follows: 
1. menu supports dark
2. dialog supports dark
3. menu icon of EnvironmentModal supports dark
4. alert confirm prompt supports dark
5. tip text of SidebarSettingsModal supports dark
The preview is as follows:

perf(ui): Improve dark theme

---

packages/ui/src/components/RequestPanel.vue
packages/ui/src/components/ResponsePanel.vue
packages/ui/src/styles/main.css

- selected tab is now more noticeable.

tweak(ui): some improvements on tabs

---

packages/ui/package-lock.json
packages/ui/package.json
packages/ui/src/components/ResponsePanel.vue
packages/ui/src/components/modals/ResponseFilteringHelpModal.vue
packages/ui/src/constants.ts

closes #151 
https://github.com/flawiddsouza/Restfox/assets/7845001/01824558-8de4-4f80-8c67-334cb6658269

feat: xml response filtering

---

packages/ui/src/components/RequestPanel.vue
packages/ui/src/components/ResponsePanelTimeline.vue
packages/ui/src/helpers.ts
packages/ui/tests/App_test.ts

fix(ui): timeline viewer display wrong info

---

packages/electron/src/app.js
packages/electron/src/preload.js
packages/ui/src/App.vue
packages/ui/src/components/modals/SettingsModal.vue
packages/ui/src/constants.ts
packages/ui/src/store.ts

feat(ui): add toggle for disable automatic updates

feat(ui): add toggle for disable automatic updates

---

packages/ui/src/components/ContextMenu.vue
packages/ui/src/components/RequestPanel.vue
packages/ui/src/components/ResponsePanel.vue
packages/ui/src/helpers.ts
packages/ui/src/styles/main.css

resolves #164 
[UI Improvement > Response History.webm](https://github.com/flawiddsouza/Restfox/assets/7845001/012c8d9a-726c-4f39-8662-bfae25d75d9a)

feat(ui): revamp the response history list

---

packages/electron/package-lock.json
packages/electron/package.json
packages/electron/src/app.js
packages/electron/src/utils/window-state.d.ts
packages/electron/src/utils/window-state.js

feat: After the window is turned off, it can save the original size. After opening the window again, it can return to the size saved before.
Use this package: https://github.com/mawie81/electron-window-state

feat(electron): support window status saving

---

packages/ui/src/components/modals/SettingsModal.vue
packages/ui/src/constants.ts
packages/ui/src/helpers.ts

feat(ui): Settings > Add Global User Agent

---

packages/ui/src/components/RequestPanel.vue
packages/ui/src/components/RequestPanelTabTitle.vue
packages/ui/src/styles/main.css

would be a great UI/UX addition to let user acknowledge if there is any script added.
https://github.com/user-attachments/assets/3bc050f1-04e3-4c4b-b655-0400768d9f01

feat(ui): Request Panel > Request Header > Script indicator

---

packages/ui/src/components/ResponsePanel.vue

fix(ui): Response Panel > Some dropped characters on Error view

---

packages/ui/src/components/NavBar.vue
packages/ui/src/helpers.ts

feat(ui): Navbar > Export as Insomnia collection

---

packages/ui/src/components/RequestPanel.vue
packages/ui/src/components/ResponsePanel.vue
packages/ui/src/components/SocketPanel.vue
packages/ui/src/components/modals/EnvironmentModal.vue
packages/ui/src/components/modals/SettingsModal.vue
packages/ui/src/constants.ts
packages/ui/src/helpers.ts

feat(ui): Settings > Indent size

---

packages/ui/src/components/ImportModal.vue
packages/ui/src/constants.ts
packages/ui/src/parsers/postman.ts

feat(ui): Import > auto detect imported file

---

packages/ui/src/components/NavBar.vue

feat(ui): disable export when collection is empty

---

packages/ui/src/components/FolderPanel.vue
packages/ui/src/components/SidebarItem.vue
packages/ui/src/components/Tab.vue
packages/ui/src/components/TabBar.vue
packages/ui/src/components/modals/SidebarSettingsModal.vue
packages/ui/src/helpers.ts

resolves #235 
@flawiddsouza Not sure if we need to remove the Folder Properties on context menu when this PR is approved.
Updated:
- clicking on folder item would open new tab to set auth and header 
- right clicking on properties to open the model to set name and path

feat(ui): folder tab view

---

packages/ui/.eslintrc.js
packages/ui/src/components/Frame.vue
packages/ui/src/components/GraphQLSchemaFetcher.vue
packages/ui/src/components/ResponsePanel.vue
packages/ui/src/components/SnippetDropdown.vue
packages/ui/src/components/TabBar.vue
packages/ui/src/components/modals/LogsModal.vue
packages/ui/src/components/modals/ResponseFilteringHelpModal.vue
packages/ui/src/components/modals/SettingsModal.vue
packages/ui/src/constants.ts
packages/ui/src/global.d.ts
packages/ui/src/helpers.ts
packages/ui/src/plugin.ts
packages/ui/src/store.ts
packages/ui/src/utils/codemirror-extensions.ts

resolves #60
- provide an option to show/hide tabs 
- add refresh button to settings modal
- add object-curly-spacing to eslint

feat(ui): Settings > Option to disable tab view

---

packages/ui/src/components/Frame.vue
packages/ui/src/components/TabBar.vue

fix(ui): active tab style

---

packages/ui/src/components/Sidebar.vue
packages/ui/src/store.ts

This PR solves #323 
A `SidebarItem` can now be dropped into the `Sidebar` itself
If the item is dropped _after_ the `sidebar-list`, it will be moved to the end of the file tree.
---
Manual test on the browser
- Google chrome: Version 136.0.7103.93
- OS: Windows 10
---
---
Let me know if anything needs to be changed!

enhancement(ui): drop side bar item to the end of tree

---

packages/ui/src/helpers.ts
packages/ui/src/store.ts
packages/ui/src/utils/generate-code.ts

Addresses #321 
When the same header name is defined multiple times, all the definitions are compressed into a comma separated list of values (according to [RFC/9110-section-5.2](https://www.rfc-editor.org/rfc/rfc9110.html#section-5.2))
On the request preview the values are not shown separately, however the original request object does have each header defined individually and parsed correctly
<details>
<summary>Original Resquest Headers (screenshot)</summary>
</details>
It also works on folders (or any parent) and the headers will follow the hierarchy order, that is, if a folder defines a header named `X-Custom-Header` as `x-value` and a request inside that folder defines `X-Custom-Header` as `y-value` the end request will have the header `x-value, y-value` (the parent is defined first) …

fix: repeated headers get dropped
