- packages/ui/package-lock.json
- packages/ui/package.json
> chore(ui): update major deps

- packages/electron/entitlements.plist
- packages/electron/forge.config.js
* Create entitlements.plist
* Update forge.config.js
Added required options in config and entitlements in an attempt to fix the current CI error.
> Fix macos notorization

- README.md
@flawiddsouza Please go over the changes. Some things might need changing.
> Update README.md with changes and documentation

- packages/ui/src/components/CodeMirrorEditor.vue
- ### Browser hotkey disabled
- `Ctrl+l`: selects address bar ( disabled to add vs-code hotkey )
- ### Codemirror hotkey disabled
- `Ctrl+Enter`: adds new line ( disabled, because same hotkey is used to send request )
- ### Codemirror hotkey enabled
- `Ctrl+l`: selects current line, on repeat selects next line ( VS-Code hotkey behavior, works only if codemirror editor is in focus  )
- Has known issue: doesn't work when cursor is at extreme right end of the text ( hope to fix in future updates )
> feat(ui): CodeMirrorEditor > disable and edit codemirror and browser hotkey

- packages/ui/src/components/Sidebar.vue
- packages/ui/src/components/SidebarItem.vue
- packages/ui/src/styles/main.css
Hello, I took the liberty of improving the sidebar ui since on MacOS it didn't look as good as it could.
after - before example
> update: enhance sidebar method ui.

- packages/ui/src/App.vue
- packages/ui/src/components/IframeFromBuffer.vue
- packages/ui/src/components/modals/SettingsModal.vue
- packages/ui/src/constants.ts
- packages/ui/src/store.ts
> feat(ui): add toggle for iframe sandbox

- packages/electron/forge.config.js
- packages/electron/package.json
fixes #112 
It would be great if a portable version could be provided in the next version.
> chore(ui): add support portable package on Windows

- packages/ui/src/components/NavBar.vue
> feat: add logo to navbar

- packages/ui/src/components/ResponsePanel.vue
> fix: this.$refs.scrollableArea.removeEventListener undefined

- packages/ui/src/components/ResponsePanelTimeline.vue
> fix(ui): ResponsePanel > ResponsePanelTab > Timeline doesnt render properly when using env var

- packages/ui/src/components/CodeMirrorSingleLine.vue
- packages/ui/src/components/RequestPanel.vue
> feat(ui): auto complete when typing an env var

- packages/ui/src/components/ContextMenu.vue
- packages/ui/src/components/RequestPanel.vue
- packages/ui/src/components/ResponsePanel.vue
resolve #159 
https://github.com/flawiddsouza/Restfox/assets/7845001/735d18d2-4171-48c4-918e-de5d922025f9
> feat(ui): request panel > body dropdown list

- packages/ui/src/components/ContextMenu.vue
- packages/ui/src/components/RequestPanel.vue
- packages/ui/src/components/RequestPanelAuth.vue
- packages/ui/src/styles/main.css
> feat(UI): Request > request auth request list

- packages/ui/src/components/ContextMenu.vue
- packages/ui/src/components/RequestPanel.vue
- packages/ui/src/components/RequestPanelAuth.vue
- packages/ui/src/components/Sidebar.vue
- packages/ui/src/components/TabBar.vue
- packages/ui/src/styles/main.css
- packages/ui/tests/steps_file.ts
[revamped UI.webm](https://github.com/user-attachments/assets/00f9f616-54a4-4ffb-a5c8-717228589c83)
> feat(ui): Sidebar Context Menu > revamped UI

- packages/ui/package-lock.json
- packages/ui/package.json
- packages/ui/src/components/GraphQLSchemaFetcher.vue
- packages/ui/src/components/RequestPanel.vue
- packages/ui/src/styles/main.css
[screen-capture.webm](https://github.com/user-attachments/assets/00dc7fb0-e85d-437d-8132-b884dc97878b)
> feat(ui): show graphql schema

- packages/ui/src/components/Sidebar.vue
- packages/ui/src/components/modals/AddGraphQLRequestModal.vue
- packages/ui/src/store.ts
- packages/ui/tests/App_test.ts
- packages/ui/tests/steps_file.ts
- adding graphql request
- adding e2e tests
> feat(ui): Sidebar > Adding graphql request

- packages/ui/src/components/RequestPanel.vue
- packages/ui/src/components/SnippetDropdown.vue
- packages/ui/src/components/modals/PluginManagerEditModal.vue
> feat(ui): built-in snippets

- packages/ui/src/components/Sidebar.vue
> fix(ui): Sidebar > Contextmenu > Missing import option

- packages/ui/src/components/RequestPanel.vue
- packages/ui/src/components/RequestPanelTabTitle.vue
would be a great UI/UX addition to let user acknowledge if there is any doc available.
> feat(ui): Request Panel > Headers > Docs indicator

- packages/ui/src/components/RequestPanel.vue
- packages/ui/src/components/RequestPanelHeaders.vue
- packages/ui/src/components/modals/HttpMethodModal.vue
- packages/ui/src/components/modals/PluginManagerEditModal.vue
resolves #101 
- bulk edit mode
- delete all headers
> feat(ui): Request Panel > Headers > Bulk Edit

- packages/ui/src/components/ResponsePanel.vue
> feat(ui): Response Panel > Response Filter > Preserve response filter

- packages/ui/src/components/ContextMenu.vue
- packages/ui/src/components/NavBar.vue
- packages/ui/src/components/RequestPanel.vue
- packages/ui/src/components/modals/EnvironmentModal.vue
- packages/ui/src/constants.ts
- packages/ui/src/helpers.ts
- packages/ui/src/web-components/alert-confirm-prompt.ts
resolves #52
- change selected indicator to fa icon
- update Env list to have its color
> feat(ui): NavBar > Environment Coloration

- packages/ui/src/components/RequestPanel.vue
- packages/ui/src/helpers.ts
- packages/ui/src/styles/main.css
- packages/ui/src/web-components/alert-confirm-prompt.ts
> feat(ui): Request Panel >  More actions for send button

- packages/ui/src/components/ImportModal.vue
- packages/ui/src/global.d.ts
- packages/ui/src/helpers.ts
resolves #217 
- importing scripts from postman collections
- converting what possible to Restfox syntax
> feat(ui): import scripts from postman collections

- packages/ui/src/components/NavBar.vue
- packages/ui/src/components/Sidebar.vue
- packages/ui/src/components/TabBar.vue
- packages/ui/src/components/modals/EnvironmentModal.vue
- packages/ui/tests/App_test.ts
- adding icons to navbar items
- consolidating the icons like close icon, export/import
- adding indicator to selected side item to make it more obvious
> feat(ui): navbar > adding icons

- packages/test-api-oauth2/app.js
> feat: support password credential

- packages/ui/src/helpers.ts
> fix: oauth2 is not applied to requests

- packages/ui/src/components/NavBar.vue
- packages/ui/src/styles/main.css
improve the way to handle the disabled custom dropdown list
> fix: disabled custom dropdown

- packages/ui/src/components/SnippetDropdown.vue
- packages/ui/src/constants.ts
- packages/ui/src/helpers.ts
- packages/ui/src/plugin.ts
> feat(ui): Script > Get response code

- packages/ui/src/components/ContextMenu.vue
- packages/ui/src/components/FolderPanel.vue
- packages/ui/src/components/ImportModal.vue
- packages/ui/src/components/Sidebar.vue
- packages/ui/src/global.d.ts
- packages/ui/src/helpers.spec.ts
- packages/ui/src/helpers.ts
- packages/ui/src/store.ts
> feat(ui): import from curl
